
# tap repositories and their packages

tap homebrew/core
brew adwaita-icon-theme
brew aom
brew assimp
brew atk
brew atomicparsley
brew autoconf
brew bat
brew bdw-gc
brew berkeley-db
brew boost
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew capstone
brew cjson
brew cmocka
brew colima
brew coreutils
brew cscope
brew dav1d
brew dbus
brew docbook
brew docbook-xsl
brew docker
brew docker-compose
brew docker-machine
brew docutils
brew double-conversion
brew easy-tag
brew eye-d3
brew fd
brew fdupes
brew ffmpeg
brew flac
brew fmt
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew giflib
brew git
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnutls
brew go
brew graphite2
brew grep
brew gsettings-desktop-schemas
brew gtk+3
brew guile
brew handbrake
brew harfbuzz
brew hicolor-icon-theme
brew highway
brew hugo
brew hunspell
brew icu4c
brew id3lib
brew id3v2
brew ilmbase
brew imagemagick
brew imageoptim-cli
brew imath
brew imlib2
brew iperf
brew iperf3
brew jasper
brew jbig2dec
brew jemalloc
brew jenv
brew jpeg-turbo
brew jpeg-xl
brew jq
brew json-glib
brew lame
brew leptonica
brew libarchive
brew libass
brew libb2
brew libbluray
brew libcaca
brew libcbor
brew libde265
brew libebml
brew libepoxy
brew libevent
brew libfido2
brew libheif
brew libid3tag
brew libidn
brew libidn2
brew liblqr
brew libmatroska
brew libmng
brew libmp3splt
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libslirp
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew lima
brew little-cms2
brew lua
brew lz4
brew lzo
brew m4
brew macvim
brew mad
brew mas
brew maven
brew mbedtls
brew md4c
brew mkvtoolnix
brew mmv
brew mp3splt
brew mp3wrap
brew mp4v2
brew mpdecimal
brew mpg123
brew multimarkdown
brew mysql
brew ncdu
brew ncurses
brew nettle
brew nlohmann-json
brew node
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjpeg
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew perl
brew pixman
brew pkg-config
brew protobuf
brew pugixml
brew pyenv
brew pyenv-virtualenv
brew pygments
brew python@3.10
brew python@3.11
brew python@3.9
brew qemu
brew qt
brew rav1e
brew rbenv
brew readline
brew rmlint
brew rubberband
brew ruby
brew ruby-build
brew sdl2
brew shared-mime-info
brew snappy
brew speex
brew sphinx-doc
brew sqlite
brew srt
brew taglib
brew tesseract
brew theora
brew tree
brew unbound
brew utf8cpp
brew vde
brew wavpack
brew webp
brew wget
brew x264
brew x265
brew xmlto
brew xorgproto
brew xvid
brew xz
brew youtube-dl
brew zeromq
brew zimg
brew zlib
brew zstd

tap homebrew/bundle

tap homebrew/cask-drivers

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask balenaetcher
cask calibre
cask filebot
cask makemkv
cask superduper
cask visual-studio-code

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask audiobookbinder

# App Store applications
appstore 1437681957  Audiobook Builder  (2.1.4)
appstore 413969927   AudioBookBinder    (2.3)
appstore 1160435653  AutoMounter        (1.7.2)
appstore 1055511498  Day One            (6.12)
appstore 563131976   mChapters          (2.2.9)
appstore 1282504627  Mimeo Photos       (4.5.0)
appstore 557168941   Tweetbot           (2.5.8)
appstore 623795237   Ulysses            (2.8.3)
